spring:
  application:
    name: restaurantreservation
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/restaurantdb?authSource=admin
      auto-index-creation: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.restaurantreservation.controller